# Pandas methods

## 1) import pandas

In [2]:
import pandas as pd

## 2) read / load data frame

In [3]:
# pd.read_csv()
# pd.read_excel()
# pd.read_json()
# pd.read_sql()
df = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")

## 5) View data

In [4]:
# first 5 rows

df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [5]:
## last 5 rows 

df.tail()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [6]:
# random rows
df.sample(5)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
167,10168,25.0,127691.0,23673,733,173618.43,0,NaN,Other,Corporate,Churn
627,10628,24.0,166441.0,5243,815,58850.36,1,Germany,Female,SME,Churn
833,10834,67.0,131931.0,45865,631,51467.32,1,UK,Male,Corporate,Churn
694,10695,51.0,45459.0,7133,536,106332.21,3,USA,Other,SME,Stay
926,10927,22.0,24929.0,32236,741,8503.39,1,India,Other,SME,Churn

In [8]:
# give number of  (rows,columns)
df.shape

(1020, 11)

In [9]:
# all columns name
df.columns

Index(['CustomerID', 'Age', 'AnnualIncome', 'Spending', 'CreditScore',
       'Balance', 'Tenure', 'Geography', 'Gender', 'Segment', 'Target'],
      dtype='object')

In [10]:
# total elements
df.size

11220

In [11]:
# row labels
df.index

RangeIndex(start=0, stop=1020, step=1)

In [12]:
# data types
df.dtypes

CustomerID        int64
Age             float64
AnnualIncome    float64
Spending          int64
CreditScore       int64
Balance         float64
Tenure            int64
Geography        object
Gender           object
Segment          object
Target           object
dtype: object

In [13]:
# summary
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [14]:
# statistics
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

# 6) Select data

In [18]:
df1 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df['Age']

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: float64

In [21]:
# single column
df[['Age']] # if you want the column name to be clearly visible as a dataframe

       Age
0     58.0
1     65.0
2     56.0
3     55.0
4     66.0
...    ...
1015  43.0
1016  25.0
1017  49.0
1018  38.0
1019  62.0

[1020 rows x 1 columns]

In [23]:
# multiple column
df[['CustomerID','Age']]

      CustomerID   Age
0          10001  58.0
1          10002  65.0
2          10003  56.0
3          10004  55.0
4          10005  66.0
...          ...   ...
1015       10450  43.0
1016       10753  25.0
1017       10810  49.0
1018       10267  38.0
1019       10059  62.0

[1020 rows x 2 columns]

In [24]:
# row selection
df.loc[0]

CustomerID        10001
Age                58.0
AnnualIncome    49184.0
Spending           2139
CreditScore         581
Balance             NaN
Tenure                2
Geography        France
Gender             Male
Segment             SME
Target             Stay
Name: 0, dtype: object

In [25]:
df.iloc[0]

CustomerID        10001
Age                58.0
AnnualIncome    49184.0
Spending           2139
CreditScore         581
Balance             NaN
Tenure                2
Geography        France
Gender             Male
Segment             SME
Target             Stay
Name: 0, dtype: object

In [27]:
df.iloc[1:5]

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [28]:
df.loc[1:5]

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.62,6,India,Other,Corporate,Stay

In [36]:
# conditions 
sf =df[df['Age'] > 60]
sf.head(14)
sf[['CustomerID','Age']]

      CustomerID   Age
1          10002  65.0
4          10005  66.0
5          10006  69.0
7          10008  67.0
11         10012  69.0
...          ...   ...
1008       10417  70.0
1010       10515  62.0
1012       10882  61.0
1013       10531  64.0
1019       10059  62.0

[203 rows x 2 columns]

# 7) Add/modify columns

In [43]:
df3 = pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")
df3.loc[0,'CustomerID'] = 12345

In [44]:
df3[['CustomerID']]

      CustomerID
0          12345
1          10002
2          10003
3          10004
4          10005
...          ...
1015       10450
1016       10753
1017       10810
1018       10267
1019       10059

[1020 rows x 1 columns]

In [46]:
df['Age2'] = df['Age'] * 2 # make a new column Age2

In [47]:
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,Age2
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,116.0
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,130.0
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,112.0
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,110.0
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,132.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay,86.0
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn,50.0
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay,98.0
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay,76.0
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn,124.0

In [49]:
df = df.assign(Bonus=df['Balance']*0.1)
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,Age2,Bonus
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,116.0,NaN
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,130.0,635.654
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,112.0,14320.392
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,110.0,13962.788
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,132.0,7598.546
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay,86.0,6035.303
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn,50.0,12451.207
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay,98.0,5385.009
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay,76.0,13810.005
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn,124.0,NaN

# 8. Rename columns

In [50]:
df8 =  pd.read_csv("C:\\Users\\deore\\Downloads\\Task_dataset - Task_dataset.csv")

In [54]:
df.rename(columns = {'Age':'AAge','CustomerID':'ID'},inplace = True)

In [57]:
df = df8.add_prefix('add_')
df.add_suffix('_add')

,add_CustomerID_add,add_Age_add,add_AnnualIncome_add,add_Spending_add,add_CreditScore_add,add_Balance_add,add_Tenure_add,add_Geography_add,add_Gender_add,add_Segment_add,add_Target_add
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

# 9) Delete data